### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by adilsoncarvalho** [damassi/babel-7-typescript-example#10]
Hi there!

First of all thanks for your post. It helped me a lot when we decided to migrate to TypeScript.

Did you face the `regeneratorRuntime is not defined` error?

I have created a class just like this one below

```typescript
export default class Teste {
  async metodo () {
    return 'ok'
  }
}
```

Then I included it along `index.tsx` as follows

```typescript
import Teste from './Teste'

const t = new Teste()
```

It does nothing and I just added there because I started to face this issue on my code and my first idea was that I failed following the steps you detailed gave on your post but, the result is the same as the ones I got on my code

```
node dist/index.js
/Users/adilson/dev/babel-7-typescript-example/dist/Teste.js:30
      regeneratorRuntime.mark(function _callee() {
      ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/adilson/dev/babel-7-typescript-example/dist/Teste.js:30:7
    at /Users/adilson/dev/babel-7-typescript-example/dist/Teste.js:48:6
    at Object.<anonymous> (/Users/adilson/dev/babel-7-typescript-example/dist/Teste.js:52:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

All the post I saw so far mention those two options:

* [@babel/plugin-transform-regenerator](https://babeljs.io/docs/en/babel-plugin-transform-regenerator) which I could not manage to get it working

* to add `@babel/polyfill` that actually works but it is a terrible option when coding a new lib as there is no _central_ import point, making the require to happen on each file

Do you have any tips on that?

Thanks!

**Comment by damassi** [comment]
Hi @adilsoncarvalho - the way to go with the latest babel is to combine `@babel/env` with [`useBuiltins`](https://github.com/artsy/positron/blob/master/.babelrc#L7). As babel is compiling, it will detect language features and only import what is needed. This allows one to remove babel-plugin-transform-runtime, too. See https://babeljs.io/docs/en/babel-preset-env#usebuiltins. 

Let me know if that works!

**Comment by damassi** [comment]
Closing due to lack of activity
