### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by krasevych** [damassi/babel-7-typescript-example#3]
I got an error
```$ babel-node --extensions '.ts,.tsx' index.ts
D:\React\examples\babel-7-typescript-example\index.ts:1
(function (exports, require, module, __filename, __dirname) { import './src/index'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (D:\React\examples\babel-7-typescript-example\node_modules\@babel\node\lib\_babel-node.js:140:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
error Command failed with exit code 1.```

**Comment by damassi** [comment]
Hi @krasevych - I just pulled this repo down and did a fresh install and all good over here. Are you sure you ran `yarn install` before running `yarn start`?

**Comment by damassi** [comment]
Let me know if this is still an issue for you!
