### ISSUE TITLE
Couldn't find preset "@babel/env" relative to directory ".../babel-7-types cript-example"

### ISSUE THREAD

**Issue by gaspard** [damassi/babel-7-typescript-example#7]
Hi there, I just cloned the repo and did an `npm i` then `npm test`. I get this:

```
$ npm test

> babel-7-typescript-example@1.0.0 test .../babel-7-typescript-example
> jest

 FAIL  src/__tests__/index.test.js
  ● Test suite failed to run

    Couldn't find preset "@babel/env" relative to directory ".../babel-7-typescript-example"

      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
```

**Comment by damassi** [comment]
Hi @gaspard - Not sure why this would be missing, but can you try to `yarn install`?

**Comment by damassi** [comment]
Closing due to non activity
