### ISSUE TITLE
Error when starting project

### ISSUE THREAD

**Issue by kewp** [damassi/babel-7-typescript-example#9]
I did the typical clone and `yarn install` and then I get an error on `yarn start`.

```
C:\Users\Karl\tst\babel-7-typescript-example>yarn start
yarn run v1.10.1
$ babel-node --extensions '.ts,.tsx' index.ts
C:\Users\Karl\tst\babel-7-typescript-example\index.ts:1
(function (exports, require, module, __filename, __dirname) { import './src/index'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at Object.<anonymous> (C:\Users\Karl\tst\babel-7-typescript-example\node_modules\@babel\node\lib\_babel-node.js:224:
23)
    at Module._compile (module.js:653:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by damassi** [comment]
Hi @kewp - this is strange! I don't have much experience with windows machines but there's no reason why this shouldn't work. I just recloned and seemed to work on my side (on OSX): 

![cap](https://user-images.githubusercontent.com/236943/47454080-19e62180-d783-11e8-9117-88ea4109e03a.gif)

The only think i can think of is there's some kind of fallback yarn `node_modules` folder that is causing a conflict with the local `node_modules` folder? 

Can you try running `npm start` and seeing what happens?

**Comment by damassi** [comment]
closing due to lack of activity.
